#!/usr/bin/env bash
#script displaying To infinity and beyond with a sleep 2 in between and displays I'm invincible!!! when SIGTERM is called

while true
do
echo "To infinity and beyond"
sleep 2
SIGTERM "I am invincible!!!"
done
