#!/usr/bin/env bash
#display Hi after line 9

COUNTER=0
while [ $COUNTER -lt 10 ]
do
if [ $COUNTER  -eq 3 ];
then
	echo "bad luck";
elif [ $COUNTER -eq 8 ];
then
	echo "good luck"
else
	echo "Holberton School"
fi;
	(( COUNTER++ ))
done
