#!/usr/bin/env bash
#display Hi after line 9

COUNTER=1
while [ $COUNTER -lt 20 ]
do
echo "$COUNTER"
case $COUNTER in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
	(( COUNTER++ ))
done
