#!/usr/bin/env bash
#Configure ufw so that it blocks all incoming traffic, except for port 22, 443
#and 80
sudo apt-get install ufw
sudo ufw disable
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
