#!/usr/bin/env bash
#fix container so that nginx runs as nginx user and is listening on port 80

pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/'/etc/nginx/sites-available/default
sudo -u nginx service nginx start
