#!/usr/bin/env bash
#fix container so that nginx runs as nginx user and is listening on port 80

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
